import { SelectableItem } from '../store/articles/articlesTypes'

const countriesData: SelectableItem[] = [
  { id: 0, short: 'ae', name: 'United Arab Emirates' },
  { id: 1, short: 'ar', name: 'Argentina' },
  { id: 2, short: 'at', name: 'Austria' },
  { id: 3, short: 'au', name: 'Australia' },
  { id: 4, short: 'be', name: 'Belgium' },
  { id: 5, short: 'bg', name: 'Bulgaria' },
  { id: 6, short: 'br', name: 'Brazil' },
  { id: 7, short: 'ca', name: 'Canada' },
  { id: 8, short: 'ch', name: 'Switzerland' },
  { id: 9, short: 'cn', name: 'China' },
  { id: 10, short: 'co', name: 'Colombia' },
  { id: 11, short: 'cu', name: 'Cuba' },
  { id: 12, short: 'cz', name: 'Czech Republic' },
  { id: 13, short: 'de', name: 'Germany' },
  { id: 14, short: 'eg', name: 'Egypt' },
  { id: 15, short: 'fr', name: 'France' },
  { id: 16, short: 'gb', name: 'United Kingdom' },
  { id: 17, short: 'gr', name: 'Greece' },
  { id: 18, short: 'hk', name: 'Hong Kong' },
  { id: 19, short: 'hu', name: 'Hungary' },
  { id: 20, short: 'id', name: 'Indonesia' },
  { id: 21, short: 'ie', name: 'Ireland' },
  { id: 22, short: 'il', name: 'Israel' },
  { id: 23, short: 'in', name: 'India' },
  { id: 24, short: 'it', name: 'Italy' },
  { id: 25, short: 'jp', name: 'Japan' },
  { id: 26, short: 'kr', name: 'South Korea' },
  { id: 27, short: 'lt', name: 'Lithuania' },
  { id: 28, short: 'lv', name: 'Latvia' },
  { id: 29, short: 'ma', name: 'Morocco' },
  { id: 30, short: 'mx', name: 'Mexico' },
  { id: 31, short: 'my', name: 'Malaysia' },
  { id: 32, short: 'ng', name: 'Nigeria' },
  { id: 33, short: 'nl', name: 'Netherlands' },
  { id: 34, short: 'no', name: 'Norway' },
  { id: 35, short: 'nz', name: 'New Zealand' },
  { id: 36, short: 'ph', name: 'Philippines' },
  { id: 37, short: 'pl', name: 'Poland' },
  { id: 38, short: 'pt', name: 'Portugal' },
  { id: 39, short: 'ro', name: 'Romania' },
  { id: 40, short: 'rs', name: 'Serbia' },
  { id: 41, short: 'ru', name: 'Russia' },
  { id: 42, short: 'sa', name: 'Saudi Arabia' },
  { id: 43, short: 'se', name: 'Sweden' },
  { id: 44, short: 'sg', name: 'Singapore' },
  { id: 45, short: 'si', name: 'Slovenia' },
  { id: 46, short: 'sk', name: 'Slovakia' },
  { id: 47, short: 'th', name: 'Thailand' },
  { id: 48, short: 'tr', name: 'Turkey' },
  { id: 49, short: 'tw', name: 'Taiwan' },
  { id: 50, short: 'ua', name: 'Ukraine' },
  { id: 51, short: 'us', name: 'United States' },
  { id: 52, short: 've', name: 'Venezuela' },
  { id: 53, short: 'za', name: 'South Africa' },
]

export default countriesData
